services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672" # RabbitMQ AMQP protocol
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
